# Generated by Django 4.2 on 2023-04-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_time', models.DateTimeField(verbose_name='入职时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='num_employees',
        ),
        migrations.AddField(
            model_name='department',
            name='title',
            field=models.CharField(default=1, max_length=32, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manage.department', verbose_name='部门'),
        ),
    ]
