# Generated by Django 4.2 on 2023-04-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0003_alter_userinfo_depart_alter_userinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='入职时间'),
        ),
    ]
