# Generated by Django 4.2 on 2023-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0005_alter_userinfo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='密码'),
        ),
    ]
