# Generated by Django 4.2 on 2023-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0010_alter_order_title_alter_order_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=32, verbose_name='部门名称')),
                ('sales', models.IntegerField(verbose_name='销售额')),
                ('file', models.CharField(max_length=128, verbose_name='部门文件')),
            ],
            options={
                'verbose_name': '业绩表',
                'verbose_name_plural': '业绩表',
            },
        ),
    ]
