# Generated by Django 4.2 on 2023-05-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0011_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('type', models.IntegerField(verbose_name='类型')),
                ('img', models.FileField(max_length=128, upload_to='Picture/', verbose_name='Logo')),
            ],
        ),
    ]
