# Generated by Django 4.2 on 2023-05-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0012_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='type',
            field=models.CharField(max_length=32, verbose_name='类型'),
        ),
    ]
